### ISSUE TITLE
Ability to use auth without TouchID

### ISSUE THREAD

**Issue by laGrave** [liu044100/SmileTouchID#10]
Is there ability to use auth functionality with TouchID disabled (for devices with TouchID sensor)? INPUT_ONCE means "turn off auth after entering password" but not "use only password authentication"

**Comment by BilalReffas** [comment]
I don't understand your question what do you mean ?

**Comment by laGrave** [comment]
In this example TouchID is enabled automatically:
if ([SmileAuthenticator hasPassword]) {
        [SmileAuthenticator sharedInstance].securityType = INPUT_TOUCHID;
        [[SmileAuthenticator sharedInstance] presentAuthViewController];
    }

But what if I want to lock app with only password (with TouchID disabled)?

**Comment by liu044100** [comment]
Hello,  laGrave.

 SmileTouchID default enable TouchID if the hardware support it, if you want to lock app with only password, maybe you can comment  the code in the `-(void)authenticateWithSuccess:(AuthCompletionBlock)authSuccessBlock andFailure:(AuthErrorBlock)failureBlock` method in  `SmileAuthenticator.m` .
