### ISSUE TITLE
Change StatusBar Style

### ISSUE THREAD

**Issue by BilalReffas** [liu044100/SmileTouchID#11]
I have a problem I would like to change the Status Bar style but it don't work I did a lot of changes in Code. Like this
`- (UIStatusBarStyle)preferredStatusBarStyle
{
    return UIStatusBarStyleLightContent;
}`

On `SmileSettingVC.m`

**Comment by liu044100** [comment]
Hello, BilalReffas.

Maybe you can refer [this link](http://stackoverflow.com/questions/19013975/ios-7-and-later-set-status-bar-style-per-view-controller).
