### ISSUE TITLE
Delay for password re-entry

### ISSUE THREAD

**Issue by DoctorG** [liu044100/SmileTouchID#18]
Is there a way you could add a setting so we can delay re-entry of password or touch ID for x number of seconds in case user task switches, answers a text makes a brief call?

**Comment by liu044100** [comment]
@DoctorG Sorry for reply later.

I will make this feature on holiday (because I have to work to make money...),  maybe three days later

**Comment by DoctorG** [comment]
Thank you!

**Comment by liu044100** [comment]
@DoctorG  sorry about it, I has been very busy recently, this feature maybe delay... but when I have free time, I will think about it...

**Comment by DoctorG** [comment]
I really appreciate it!  Thanks again for this great library!!

**Comment by liu044100** [comment]
@DoctorG Sorry for being late, I have add the new property `NSTimeInterval timeoutInterval` in the class `SmileAuthenticator` and update pod to `0.1.7`. You can set the interval you want for delay re-entry of password or touch ID.

**Comment by DoctorG** [comment]
You are the best!  Thank you again for sharing your awesome library!!
