### ISSUE TITLE
Commented SecItemAdd and SecItemUpdate methods

### ISSUE THREAD

**Issue by alexruperez** [liu044100/SmileTouchID#2]
Doesn't store anything in keychain.

https://github.com/liu044100/SmileTouchID/blob/master/SmileAuth/Classes/SmileKeychainWrapper.m#L245

Remember updated the pod. :)

**Comment by liu044100** [comment]
Sorry about it, it is my mistake, Cocoapods show this line has unused error code, so I uncomment it and no more think about it,  sorry about it.

Now I have fixed it. Thank your very much.
