### ISSUE TITLE
When cancelling the Touch ID input, the keyboard is invisible

### ISSUE THREAD

**Issue by stuville** [liu044100/SmileTouchID#21]
In the latest release, if you cancel the Touch ID in the sample application and in own application, the keyboard is not shown but can accept input. Weird!

Xcode 8.1 Beta 3 and iOS 10 beta 3

**Comment by stuville** [comment]
Update.  Issues with the Beta. Have to add a slight delay for [self.passwordField becomeFirstResponder];

**Comment by liu044100** [comment]
@stuville Sorry for the late reply, thanks for open this issue.

It is wired... I tested in the simulator and it works well, but in real device this issue happened,  I also noticed the PR #20, I will test it, and update pod as soon as possible.

**Comment by liu044100** [comment]
@stuville the pod has been updated to 0.1.8 that fix this issue.

**Comment by stuville** [comment]
Thanks!!!!
