### ISSUE TITLE
Don't make the change password process

### ISSUE THREAD

**Issue by BilalReffas** [liu044100/SmileTouchID#9]
I have a problem I wrote this with swift
 `SmileAuthenticator.sharedInstance().securityType = SecurityType.INPUT_THREE
        SmileAuthenticator.sharedInstance().tintColor = UIColor(red:0.15, green:0.67, blue:0.42, alpha:1)
        dispatch_async(dispatch_get_main_queue()){
            SmileAuthenticator.sharedInstance().presentAuthViewControllerAnimated(true)
  }`

To go to the password change process but it don't work nothing happened. He just ask for an password one time thats it

**Comment by liu044100** [comment]
Could you give me a example project? I want to get more detail.

**Comment by BilalReffas** [comment]
how you mean that ?:) I just use the same code to change the password. 
`SmileAuthenticator.sharedInstance().securityType = .INPUT_THREE`
`SmileAuthenticator.sharedInstance().presentAuthViewControllerAnimated(true)`

The only think it's written in swift

**Comment by liu044100** [comment]
`[SmileAuthenticator sharedInstance].rootVC` the rootVC is correct?

Maybe you can use the [Xcode View debug](http://www.raywenderlich.com/98356/view-debugging-in-xcode-6) that help to check whether the presented view controller is covered by other View.

**Comment by BilalReffas** [comment]
Yes I put this on the AppDelegate didFinishLaunchingWithOptions
`SmileAuthenticator.sharedInstance().rootVC = self.window?.rootViewController`

**Comment by liu044100** [comment]
I made a swift project just now and test it, `SmileAuthenticator.sharedInstance().presentAuthViewControllerAnimated(true)` works, it will be appreciated if you can give me more detail about the context when use `presentAuthViewControllerAnimated(true)`.

Could you make a simple demo project reappear the issue?

**Comment by BilalReffas** [comment]
It's because I have more views. It only works on one view like on the demo

**Comment by BilalReffas** [comment]
You have to do this `SmileAuthenticator.sharedInstance().rootVC = self`
On every view you have.

**Comment by liu044100** [comment]
I made a very [simple demo project](http://bit.ly/1OrSc2v) to show `SmileAuthenticator.sharedInstance().presentAuthViewControllerAnimated(true)`  on two tab, it works.

Maybe you use it to reappear your issue.
